export default {
  tomatogrotesk: {
    black: "TomatoGrotesk-Black",
    blackItalic: "TomatoGrotesk-BlackSlanted",
    bold: "TomatoGrotesk-Bold",
    boldItalic: "TomatoGrotesk-BoldSlanted",
    extraBold: "TomatoGrotesk-ExtraBold",
    extraBoldItalic: "TomatoGrotesk-ExtraBoldSlanted",
    extraLight: "TomatoGrotesk-ExtraLight",
    extraLightItalic: "TomatoGrotesk-ExtraLightSlanted",
    italic: "TomatoGrotesk-Slanted",
    light: "TomatoGrotesk-Light",
    lightItalic: "TomatoGrotesk-LightSlanted",
    medium: "TomatoGrotesk-Medium",
    mediumItalic: "TomatoGrotesk-MediumSlanted",
    regular: "TomatoGrotesk-Regular",
    semiBold: "TomatoGrotesk-SemiBold",
    semiBoldItalic: "TomatoGrotesk-SemiBoldSlanted",
    thin: "TomatoGrotesk-Thin",
    thinItalic: "TomatoGrotesk-ThinSlanted",
  },
  dmsans: {
    black: "DMSans-Black",
    blackItalic: "DMSans-BlackItalic",
    bold: "DMSans-Bold",
    boldItalic: "DMSans-BoldItalic",
    extraBold: "DMSans-ExtraBold",
    extraBoldItalic: "DMSans-ExtraBoldItalic",
    extraLight: "DMSans-ExtraLight",
    extraLightItalic: "DMSans-ExtraLightItalic",
    italic: "DMSans-Italic",
    light: "DMSans-Light",
    lightItalic: "DMSans-LightItalic",
    medium: "DMSans-Medium",
    mediumItalic: "DMSans-MediumItalic",
    regular: "DMSans-Regular",
    semiBold: "DMSans-SemiBold",
    semiBoldItalic: "DMSans-SemiBoldItalic",
    thin: "DMSans-Thin",
    thinItalic: "DMSans-ThinItalic",
  },
};
